# Generated by Django 2.2.2 on 2019-08-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_index=True)),
                ('privacy', models.PositiveSmallIntegerField(choices=[('PRIVATE', 0), ('TRUSTED', 1), ('PUBLIC', 2)])),
            ],
        ),
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=1024, unique=True)),
                ('public_key', models.CharField(max_length=2048)),
            ],
        ),
    ]
