# Generated by Django 2.2.2 on 2019-08-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='', max_length=512, unique=True),
            preserve_default=False,
        ),
    ]
